%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
# dataset_dir: /media/xiang/Data/Dataset/Kitti/dataset/sequences/00
dataset_dir: /mnt/d/Bowen/Study/SLAM/dataset/KITTI/sequences/00
vocabulary_dir: /home/zbw/berwinz/stereo_vo_bknd/vocabulary/ORBvoc.txt

# camera intrinsics
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7
# Camera.fx: 718.856
# Camera.fy: 718.856
# Camera.cx: 607.1928
# Camera.cy: 185.2157

num_features: 200                      # max number of ORB detector could retain
scale_factor: 1.2
level_pyramid: 8
num_features_init: 150                 # number to initialize the map
num_features_tracking: 150             # consider whether tracking good or bad
num_features_tracking_bad_: 20         # consider whether tracking back or lost
num_features_needed_for_keyframe: 150  # consider when to determine a new keyframe
num_active_keyframes: 5                # active keyframes kept in map
chi2_th: 5.991                         # scale to determine outlier in loopclosing